config: |
  global  
    maxconn 100  
   
  defaults  
      log global  
      mode tcp  
      retries 2  
      timeout client 30m  
      timeout connect 4s  
      timeout server 30m  
      timeout check 5s  
    
  listen stats  
      mode http  
      bind *:7000  
      stats enable  
      stats uri /  
    
  listen ReadWrite  
      bind *:5432
      mode tcp
      server acid-minimal-cluster.default.svc.cluster.local acid-minimal-cluster.default.svc.cluster.local:5432 maxconn 100 check